### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by GregPlowman** [jump-dev/Cbc.jl#144]
Can a new release be made for Cbc?

Unfortunately it seems we're playing whack-a-mole with versioning.
The recent `Clp` upgrade caused `Cbc` to downgrade from `0.7.0` to `0.6.7`
I think this is indirectly because `CEnum 0.4` is not allowed on `Cbc 0.7.0`, but has already been updated on `Cbc` master.

**Comment by odow** [comment]
> we're playing whack-a-mole with versioning.

Yes, I understand the frustration. We hope to have an announcement in the near future that should significantly alleviate these issues.

**Comment by odow** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/21333
