### ISSUE TITLE
JuMP cannot fix variable values from cbc solutions: LoadError: JuMP.OptimizeNotCalled()

### ISSUE THREAD

**Issue by xuqingyu** [jump-dev/Cbc.jl#170]
Dear Cbc team,
Thank you for reading! 
We are facing an error thrown by JuMP while solving MILP using Cbc and we are hoping to get your help!
Here is the error description. We solved a MILP and we want to fix the values of integer variables and resolve the problem as an LP. To finish the job, we did: (the the model name is EP)
```julia
optimize!(EP)
for v in all_variables(EP)
 if is_integer(v)
    unset_integer(v)
    fix(v,value(v),force=true)
 elseif is_binary(v)
    unset_binary(v)
    fix(v,value(v),force=true)
 end
end
```
The code will throw an error like the following:
`MILP solved for primal`
`ERROR: LoadError: LoadError: JuMP.OptimizeNotCalled()`
`Stacktrace:`
`[1] _moi_get_result(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.GenericModel{Float64,MathOptInterface.Utilities.ModelFunctionConstraints{Float64}}}}, ::MathOptInterface.VariablePrimal, ::Vararg{Any,N} where N) at /Users/qingyuxu/.julia/packages/JuMP/YXK4e/src/JuMP.jl:845`
`[2] get(::JuMP.Model, ::MathOptInterface.VariablePrimal, ::JuMP.VariableRef) at /Users/qingyuxu/.julia/packages/JuMP/YXK4e/src/JuMP.jl:877`
`[3] #value#28(::Int64, ::typeof(JuMP.value), ::JuMP.VariableRef) at /Users/qingyuxu/.julia/packages/JuMP/YXK4e/src/variables.jl:767`
`[4] value at /Users/qingyuxu/.julia/packages/JuMP/YXK4e/src/variables.jl:767 [inlined]`

We are sure that the model can solve without the fixing integer part. So we guess it is a problem of using `fix` function on the solutions obtained by cbc.
We are using:
```julia
  "JuMP"            => v"0.21.3"
  "MathProgBase"    => v"0.7.8"
  "Cbc"             => v"0.8.0"
```
Thank you,
Qingyu

**Comment by blegat** [comment]
See the warning in https://jump.dev/JuMP.jl/stable/manual/solutions/#Recommended-workflow.
Once you call `unset_binary` or `unset_integer`, the problem has changed hence the solution of the solver is not valid anymore and you need to resolve to get a new solution so when you call `value`, it throws `OptimizerNotCalled`.
You should get all the values you need first and store them in some way and then modify afterwards.

**Comment by xuqingyu** [comment]
Thank you! But when we use gurobi, there is no problem at all using the same process, so can I say this issue is cbc specific?

**Comment by xuqingyu** [comment]
Dear Blegat,
Thanks for your reply. We reversed the order of the code, but the code still failed at the fixing variable stage.
```julia
optimize!(EP)
for v in all_variables(EP)
 if is_integer(v)
    fix(v,value(v),force=true)
    unset_integer(v)
 elseif is_binary(v)
    fix(v,value(v),force=true)
    unset_integer(v)
 end
end
```

**Comment by xuqingyu** [comment]
@blegat Dear Benoît, a quick update. This does not work either.
```julia
optimize!(EP)
for v in all_variables(EP)
 if is_integer(v)
    value(v)
 elseif is_binary(v)
    value(v)
 end
end
```

**Comment by blegat** [comment]
> But when we use gurobi, there is no problem at all using the same process, so can I say this issue is cbc specific?

As written in the docs: https://jump.dev/JuMP.jl/stable/manual/solutions/#Recommended-workflow
This is undefined behavior.

> We reversed the order of the code, but the code still failed at the fixing variable stage.

You should query all values first like
```julia
optimize!(EP)
values = Dict(v => value(v))
for v in all_variables(EP)
    if is_integer(v)
        unset_integer(v)
        fix(v,values[v],force=true)
    elseif is_binary(v)
        unset_binary(v)
        fix(v,values[v],force=true)
    end
end
```

**Comment by xuqingyu** [comment]
@blegat Dear Benoît, thanks for your advice. We followed it with a little modification and it works. Please see the functional code below. 
```julia
    optimize!(EP)
    values = Dict(v => value(v) for v in all_variables(jump_model))
    for v in all_variables(jump_model)
        if is_integer(v)
            unset_integer(v)
            fix(v,values[v],force=true)
        elseif is_binary(v)
            unset_binary(v)
            fix(v,values[v],force=true)
        end
    end
```
