### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by bertrandhaut** [jump-dev/Cbc.jl#174]
In the options section of the readme.md you wrote

> ratioGap -- Terminate after optimality gap is smaller than this relative fraction.
> For example, set_optimizer_attribute(model, "allowableGap", 0.05).

it should be read as 

> ratioGap -- Terminate after optimality gap is smaller than this relative fraction.
> For example, set_optimizer_attribute(model, "**ratioGap**", 0.05).

**Comment by odow** [comment]
Thanks
