### ISSUE TITLE
How to get the current solution in the case of TIME_LIMIT?

### ISSUE THREAD

**Issue by ShuhuaGao** [jump-dev/Cbc.jl#200]
When the optimization terminates due to timeout (that is, `termination_status(model) = TIME_LIMIT`), Gurobi.jl can still give a non-optimal possible solution, e.g., by `x = value.(model[:x])`. However, Cbc.jl will fail in the same case and throw an error below:
`Result index of attribute MathOptInterface.VariablePrimal(1) out of bounds. There are currently 0 solution(s) in the model.`

Even if I double the time of Cbc.jl, the same issue occurs. I suppose that Cbc should be able to find a solution, though not optimal, after its timeout.
Is this result attributed to Cbc itself or the API of Cbc.jl?

**Comment by blegat** [comment]
Is there any integer variables ?

If there are 0 solutions it means this returns zero:
https://github.com/jump-dev/Cbc.jl/blob/3db1f16751a18d4f200b15bfd6116925fbdfddb0/src/MOI_wrapper/MOI_wrapper.jl#L629-L636

See [`Cbc_numberSavedSolutions`](https://www.coin-or.org/Doxygen/Cbc/classCbcModel.html#a22dba737a990820822f540dcc81eac42)

**Comment by blegat** [comment]
It seems we're calling the `C` Cbc function so it's indeed what the internal solvers says.
You can try `Cbc.Cbc_numberSavedSolutions(JuMP.unsafe_backend(model))` where `model` is the JuMP model to make sure of it.

**Comment by odow** [comment]
Cbc.jl will provide a suboptimal solution if Cbc has one to report. There are a variety of reasons that this might not be the case, so it's hard to give more advice without a reproducible example and the solver log.

If you need to use an open-source MILP solver, try HiGHS.jl instead.

**Comment by ShuhuaGao** [comment]
OK. Thank you for the advice. I will check HiGHS.jl.
