### ISSUE TITLE
Cbc 2.10.8

### ISSUE THREAD

**Issue by Wikunia** [jump-dev/Cbc.jl#212]
I'm currently getting an error that the Cbc version installed is too new.

```
ERROR: LoadError: You have installed version 2.10.8 of Cbc, which is not supported by
Cbc.jl We require Cbc version 2.10. After installing Cbc 2.10, run:

    import Pkg
    Pkg.rm("Cbc")
    Pkg.add("Cbc")

If you have a newer version of Cbc installed, changes may need to be made
to the Julia code. Please open an issue at
https://github.com/jump-dev/Cbc.jl.
```

Is there anything I can do to still use Cbc.jl without an updated version?

**Comment by odow** [comment]
What is `import Pkg; Pkg.status()`?

I don't understand this error. It should work fine. If `version = v"2.10.8"`, I don't see how this error is triggered:

https://github.com/jump-dev/Cbc.jl/blob/84551568c6ac3d6efd997d546710efe88beb0620/src/Cbc.jl#L22-L25

**Comment by lucapizzimbone** [comment]
I am getting similar error:
uliaError: Exception 'LoadError: You have installed version 2.10.8 of Cbc, which is not supported by
Cbc.jl We require Cbc version 2.10. After installing Cbc 2.10, run:

    import Pkg
    Pkg.rm("Cbc")
    Pkg.add("Cbc")

If you have a newer version of Cbc installed, changes may need to be made
to the Julia code. Please open an issue at
https://github.com/jump-dev/Cbc.jl.

**Comment by odow** [comment]
You have installed an old version of Cbc.jl (the Julia package). You need to install at least Cbc.jl@1.0.3. The installation issue was fixed here: https://github.com/jump-dev/Cbc.jl/pull/206

Try
```Julia
import Pkg
Pkg.pkg"add Cbc@1.0.3"
```

**Comment by odow** [comment]
Ah. Your issue is that PandaModels requires an old version of Cbc: https://github.com/e2nIEE/PandaModels.jl/blob/b8cb4e438525e6c128d832f7aa7bf70afda9b9b9/Project.toml#L18-L26

PandaModels.jl should be updated, but I'll also fix the compat bounds in the registry:

https://github.com/JuliaRegistries/General/pull/75017

**Comment by odow** [comment]
Fixed in general, so we shouldn't get this issue again.
